### ISSUE TITLE
Is there any way to contact with you? 

### ISSUE THREAD

**Issue by aolmospersonal** [dfwteinos/Instagram-Comment-Bot#1]
Hello, 
Is there any way to contact with you?

**Comment by dfwteinos** [comment]
Hello, here is my email: 
dimfwteinos@gmail.com

**Comment by aolmosasir** [comment]
> Hello, here is my email:
> [dimfwteinos@gmail.com](mailto:dimfwteinos@gmail.com)

Sent you a message, thanks!

**Comment by aolmospersonal** [comment]
> Hello, here is my email:
> [dimfwteinos@gmail.com](mailto:dimfwteinos@gmail.com)

Sent you a message, thanks!
